/*
 * font.h
 * (c)2010-2015 Seiji Nishimura, Based on OpenBSD banner command
 * $Id: font.h,v 1.1.1.2 2015/01/14 00:00:00 seiji Exp seiji $
 */
/*
 *      Various defines needed for code lifted from lpd.
 *
 *      @(#)Copyright (c) 1995, Simon J. Gerraty.
 *
 *      This is free software.  It comes with NO WARRANTY.
 *      Permission to use, modify and distribute this source code
 *      is granted subject to the following conditions.
 *      1/ that the above copyright notice and this notice
 *      are preserved in all copies and that due credit be given
 *      to the author.
 *      2/ that any changes to this code are clearly commented
 *      as such so that the author does not get blamed for bugs
 *      other than his own.
 *
 *      Please send copies of changes and bug-fixes to:
 *      sjg@zen.void.oz.au
 */
/*
 * Copyright (c) 1983, 1993
 *	The Regents of the University of California.  All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 * 1. Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the distribution.
 * 3. Neither the name of the University nor the names of its contributors
 *    may be used to endorse or promote products derived from this software
 *    without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE REGENTS AND CONTRIBUTORS ``AS IS'' AND
 * ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED.  IN NO EVENT SHALL THE REGENTS OR CONTRIBUTORS BE LIABLE
 * FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
 * DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
 * OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
 * HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
 * OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
 * SUCH DAMAGE.
 */

#if !defined(__PIXMAP_FONT_H__) && defined(__PIXMAP_INTERNAL__)
#    define  __PIXMAP_FONT_H__

/*      $OpenBSD: banner.c,v 1.8 2003/06/10 00:00:00 deraadt Exp $      */
/*      $NetBSD: banner.c,v 1.2 1995/04/09 00:00:00 cgd Exp $           */

#define FOREGND	'#'
#define BACKGND	' '
#define INVALID	0x7f	/* rub-out */

/*      $OpenBSD: chset.c,v 1.4 2003/06/03 00:00:00 millert Exp $       */
/*      $NetBSD: chset.c,v 1.2 1995/04/09 00:00:00 cgd Exp $            */

/* <sjg> the following were all re-generated by a perl script,
 * to fill in the gaps needed by the banner(1) char set.
 */
#define c_______	0x00
#define c______1	0x01
#define c_____1_	0x02
#define c_____11	0x03
#define c____1__	0x04
#define c____1_1	0x05
#define c____11_	0x06
#define c____111	0x07
#define c___1___	0x08
#define c___1__1	0x09
#define c___1_1_	0x0a
#define c___1_11	0x0b
#define c___11__	0x0c
#define c___11_1	0x0d
#define c___111_	0x0e
#define c___1111	0x0f
#define c__1____	0x10
#define c__1___1	0x11
#define c__1__1_	0x12
#define c__1__11	0x13
#define c__1_1__	0x14
#define c__1_1_1	0x15
#define c__1_11_	0x16
#define c__1_111	0x17
#define c__11___	0x18
#define c__11__1	0x19
#define c__11_1_	0x1a
#define c__11_11	0x1b
#define c__111__	0x1c
#define c__111_1	0x1d
#define c__1111_	0x1e
#define c__11111	0x1f
#define c_1_____	0x20
#define c_1____1	0x21
#define c_1___1_	0x22
#define c_1___11	0x23
#define c_1__1__	0x24
#define c_1__1_1	0x25
#define c_1__11_	0x26
#define c_1__111	0x27
#define c_1_1___	0x28
#define c_1_1__1	0x29
#define c_1_1_1_	0x2a
#define c_1_1_11	0x2b
#define c_1_11__	0x2c
#define c_1_11_1	0x2d
#define c_1_111_	0x2e
#define c_1_1111	0x2f
#define c_11____	0x30
#define c_11___1	0x31
#define c_11__1_	0x32
#define c_11__11	0x33
#define c_11_1__	0x34
#define c_11_1_1	0x35
#define c_11_11_	0x36
#define c_11_111	0x37
#define c_111___	0x38
#define c_111__1	0x39
#define c_111_1_	0x3a
#define c_111_11	0x3b
#define c_1111__	0x3c
#define c_1111_1	0x3d
#define c_11111_	0x3e
#define c_111111	0x3f
#define c1______	0x40
#define c1_____1	0x41
#define c1____1_	0x42
#define c1____11	0x43
#define c1___1__	0x44
#define c1___1_1	0x45
#define c1___11_	0x46
#define c1___111	0x47
#define c1__1___	0x48
#define c1__1__1	0x49
#define c1__1_1_	0x4a
#define c1__1_11	0x4b
#define c1__11__	0x4c
#define c1__11_1	0x4d
#define c1__111_	0x4e
#define c1__1111	0x4f
#define c1_1____	0x50
#define c1_1___1	0x51
#define c1_1__1_	0x52
#define c1_1__11	0x53
#define c1_1_1__	0x54
#define c1_1_1_1	0x55
#define c1_1_11_	0x56
#define c1_1_111	0x57
#define c1_11___	0x58
#define c1_11__1	0x59
#define c1_11_1_	0x5a
#define c1_11_11	0x5b
#define c1_111__	0x5c
#define c1_111_1	0x5d
#define c1_1111_	0x5e
#define c1_11111	0x5f
#define c11_____	0x60
#define c11____1	0x61
#define c11___1_	0x62
#define c11___11	0x63
#define c11__1__	0x64
#define c11__1_1	0x65
#define c11__11_	0x66
#define c11__111	0x67
#define c11_1___	0x68
#define c11_1__1	0x69
#define c11_1_1_	0x6a
#define c11_1_11	0x6b
#define c11_11__	0x6c
#define c11_11_1	0x6d
#define c11_111_	0x6e
#define c11_1111	0x6f
#define c111____	0x70
#define c111___1	0x71
#define c111__1_	0x72
#define c111__11	0x73
#define c111_1__	0x74
#define c111_1_1	0x75
#define c111_11_	0x76
#define c111_111	0x77
#define c1111___	0x78
#define c1111__1	0x79
#define c1111_1_	0x7a
#define c1111_11	0x7b
#define c11111__	0x7c
#define c11111_1	0x7d
#define c111111_	0x7e
#define c1111111	0x7f

#if        FONT_SET == 1
#include "font_lpd.h"
#else	/* FONT_SET == 0 */
#include "font_banner.h"
#endif

#endif
